import { Home, HeartPulse, Utensils, Dumbbell, Sparkles, ChartNoAxesCombined, FileText, UserRound, Crown } from 'lucide-react'
import { NavLink, Outlet } from 'react-router-dom'
import { Brand } from '@/components/Brand'
import { cn } from '@/lib/utils'

const items = [
  { label: 'Home', to: '/app/dashboard', icon: Home }, { label: 'Check-In', to: '/app/check-in', icon: HeartPulse }, { label: 'Meals', to: '/app/meals', icon: Utensils }, { label: 'Workout', to: '/app/workout', icon: Dumbbell }, { label: 'Coach', to: '/app/coach', icon: Sparkles }, { label: 'Progress', to: '/app/progress', icon: ChartNoAxesCombined }, { label: 'Reports', to: '/app/reports', icon: FileText }, { label: 'Profile', to: '/app/profile', icon: UserRound },
]
export function AppLayout() { return <div className="min-h-screen bg-canvas md:flex"><aside className="sticky top-0 hidden h-screen w-68 shrink-0 flex-col border-r border-forest/10 bg-white px-5 py-7 md:flex"><Brand /><nav className="mt-12 space-y-1">{items.map(({ label, to, icon: Icon }) => <NavItem key={to} label={label} to={to} Icon={Icon} />)}</nav><div className="mt-auto rounded-3xl bg-sand/70 p-4"><Crown className="text-nuraa" size={20} /><p className="mt-3 text-sm font-semibold text-forest">Nuraa Pro is on its way</p><p className="mt-1 text-xs leading-5 text-forest/65">Your health foundation is ready for what comes next.</p></div></aside><main className="min-w-0 flex-1 pb-24 md:pb-0"><Outlet /></main><nav className="fixed inset-x-0 bottom-0 z-30 flex h-18 items-center justify-around border-t border-forest/10 bg-white/95 px-1 backdrop-blur md:hidden">{items.map(({ label, to, icon: Icon }) => <NavItem key={to} label={label} to={to} Icon={Icon} mobile />)}</nav></div> }
function NavItem({ label, to, Icon, mobile = false }: { label: string; to: string; Icon: typeof Home; mobile?: boolean }) { return <NavLink to={to} className={({ isActive }) => cn('flex items-center gap-3 rounded-2xl font-medium transition', mobile ? 'flex-col gap-0.5 px-1 py-1 text-[10px]' : 'px-3 py-2.5 text-sm', isActive ? 'bg-sage text-nuraa' : 'text-forest/65 hover:bg-sage/60 hover:text-forest')}><Icon size={mobile ? 19 : 19} strokeWidth={1.8} /><span>{label}</span></NavLink> }
